### ISSUE TITLE
Sample cards don't render as cards in gchat

### ISSUE THREAD

**Issue by ameowlia** [spring-io/google-chat-notify-resource#2]
I set up a pipeline to publish the sample cards you have in this repo...

```yml
---
groups:
- name: testing
  jobs:
    - test-card

resource_types:
- name: google-chat-notify-resource
  type: registry-image
  source:
    repository:  us-west2-docker.pkg.dev/mapbu-cryogenics/dockerhub-proxy-cache/springio/google-chat-notify-resource
    username: _json_key
    password: ((REDACT))
    tag: 0.0.1-SNAPSHOT

resources:
- name: gchat-notification
  type: google-chat-notify-resource
  source:
    url: ((REDACT))

- name: gchat-notification-github-repo
  type: git
  icon: source-branch
  source:
    uri: git@github.com:spring-io/google-chat-notify-resource.git
    private_key: ((REDACT))
    branch: main

jobs:
- name: test-card
  plan:
  - get: gchat-notification-github-repo
  - put: gchat-notification
    params:
      text_file: gchat-notification-github-repo/samples/simple/notify/card-success.json

```

This results in the following being published to gchat...

![image](https://github.com/user-attachments/assets/57969c09-fe83-4564-bbed-5abba0fd89a6)

❓ Can you confirm that there is a bug with cards or provide a sample pipeline that publishes these cards correctly? 

I would love to be able to use cards to do some nice gchat things, but haven't been able to figure it out.
